#!/usr/bin/env python3
"""Generate FP8 lookup tables for OpenCL and CPU backends (ADR-025 §6.1).

Usage:
  # Generate OpenCL header:
  python scripts/generate_fp8_lut.py --backend opencl --output kernels/fp8_lut.gen.h

  # Generate CPU header:
  python scripts/generate_fp8_lut.py --backend cpu --output src/backends/cpu/kernel_sources/cpu_fp8_lut.gen.h

Note: The Vulkan backend uses arithmetic conversion (bit manipulation + exp2())
instead of lookup tables. See Phase 9D Technical Notes for rationale. Do NOT
add a --backend vulkan option.

Regenerate whenever ml_dtypes version changes.
"""

import argparse
import math
from pathlib import Path

import ml_dtypes
import numpy as np


def generate_e4m3_lut() -> list[float]:
    """Generate E4M3 → float32 lookup table (256 entries)."""
    values = []
    for i in range(256):
        arr = np.array([i], dtype=np.uint8).view(ml_dtypes.float8_e4m3fn)
        values.append(float(arr[0]))
    return values


def generate_e5m2_lut() -> list[float]:
    """Generate E5M2 → float32 lookup table (256 entries)."""
    values = []
    for i in range(256):
        arr = np.array([i], dtype=np.uint8).view(ml_dtypes.float8_e5m2)
        values.append(float(arr[0]))
    return values


def format_c_float(v: float) -> str:
    """Format a float for C, handling inf/NaN specially.

    Note: E5M2 includes inf/NaN bit patterns (indices 0x7C-0x7F, 0xFC-0xFF),
    but the store path NEVER writes these. We use max finite value as a
    defensive fallback — loading these indices returns a finite value rather
    than crashing or producing undefined behavior.
    """
    if math.isnan(v):
        return "0.0f"  # NaN → zero (defensive; should never be loaded)
    elif math.isinf(v):
        if v > 0:
            return "57344.0f"  # +inf → E5M2 max finite (defensive)
        else:
            return "-57344.0f"  # -inf → E5M2 min finite (defensive)
    else:
        return f"{v:.10e}f"


def format_c_array(name: str, values: list[float], is_opencl: bool = False) -> str:
    """Format lookup table as C/OpenCL constant array."""
    qualifier = "__constant" if is_opencl else "static const"
    rows = []
    for i in range(0, 256, 8):
        row = ", ".join(format_c_float(v) for v in values[i:i + 8])
        rows.append(f"    {row}")
    body = ",\n".join(rows)  # Join rows with commas between (none trailing)
    return f"{qualifier} float {name}[256] = {{\n{body}\n}};"


def _get_ml_dtypes_version() -> str:
    """Get ml_dtypes version, with fallback for older versions."""
    try:
        return ml_dtypes.__version__
    except AttributeError:
        return "unknown (pre-0.2.0)"


def generate_header(e4m3_values: list[float], e5m2_values: list[float],
                    is_opencl: bool, output_path: Path) -> None:
    """Generate a complete header file with both lookup tables."""
    guard = "FP8_LUT_CPU_GEN_H" if not is_opencl else "FP8_LUT_OPENCL_GEN_H"
    array_prefix = "cpu_" if not is_opencl else ""
    ml_version = _get_ml_dtypes_version()
    header = f"""\
/* Auto-generated by scripts/generate_fp8_lut.py — DO NOT EDIT
 * ml_dtypes version: {ml_version}
 * Regenerate with: python scripts/generate_fp8_lut.py --backend {'opencl' if is_opencl else 'cpu'} --output {output_path}
 */

#ifndef {guard}
#define {guard}

/* E4M3: sign(1) + exp(4) + mantissa(3), bias=7, max=448, no inf
 * Note: float8_e4m3fn has 2 NaN patterns (0x7F, 0xFF) and 254 finite values.
 * The store path never writes NaN patterns; the LUT maps them to 0.0f defensively.
 *
 * Index derivation examples:
 *   0x00 = 0b00000000 → sign=0, exp=0, mant=0 → subnormal 0 × 2^(-6) = 0.0
 *   0x38 = 0b00111000 → sign=0, exp=7, mant=0 → 2^(7-7) × 1.0 = 1.0
 *   0x3C = 0b00111100 → sign=0, exp=7, mant=4 → 2^(7-7) × 1.5 = 1.5
 *   0x7E = 0b01111110 → sign=0, exp=15, mant=6 → 2^(15-7) × 1.75 = 448.0 (max)
 *   0x7F = 0b01111111 → NaN (mapped to 0.0f in LUT)
 *   0x80 = 0b10000000 → sign=1, exp=0, mant=0 → -0.0
 *   0xB8 = 0b10111000 → sign=1, exp=7, mant=0 → -1.0
 *   0xFE = 0b11111110 → sign=1, exp=15, mant=6 → -448.0 (min)
 *   0xFF = 0b11111111 → NaN (mapped to 0.0f in LUT)
 */
{format_c_array(f"{array_prefix}fp8_e4m3_to_float_lut", e4m3_values, is_opencl)}

/* E5M2: sign(1) + exp(5) + mantissa(2), bias=15, max=57344, IEEE-like inf/NaN
 *
 * Unlike E4M3fn, E5M2 follows IEEE conventions for exponent 0x1F (all ones):
 *   mantissa=0 → ±infinity, mantissa≠0 → NaN.
 * This means 8 bit patterns are non-finite: 0x7C–0x7F (+inf/NaN), 0xFC–0xFF (−inf/NaN).
 * The store path never writes these patterns (it saturates to 0x7B/0xFB),
 * but the LUT includes them for completeness — callers should not rely on
 * loading non-finite values from FP8 buffers.
 *
 * Index derivation examples:
 *   0x00 = 0b00000000 → sign=0, exp=0, mant=0 → subnormal 0 × 2^(-14) = 0.0
 *   0x3C = 0b00111100 → sign=0, exp=15, mant=0 → 2^(15-15) × 1.0 = 1.0
 *   0x7B = 0b01111011 → sign=0, exp=30, mant=3 → 2^(30-15) × 1.75 = 57344.0 (max finite)
 *   0x7C = 0b01111100 → sign=0, exp=31, mant=0 → +infinity
 *   0x7D = 0b01111101 → sign=0, exp=31, mant=1 → NaN
 *   0x80 = 0b10000000 → sign=1, exp=0, mant=0 → -0.0
 *   0xBC = 0b10111100 → sign=1, exp=15, mant=0 → -1.0
 *   0xFB = 0b11111011 → sign=1, exp=30, mant=3 → -57344.0 (min finite)
 */
{format_c_array(f"{array_prefix}fp8_e5m2_to_float_lut", e5m2_values, is_opencl)}

#endif /* {guard} */
"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header)
    print(f"Generated: {output_path}")


def validate_tables(e4m3: list[float], e5m2: list[float]) -> None:
    """Validate LUT correctness against known values."""
    # E4M3 positive values
    assert e4m3[0] == 0.0, "E4M3 index 0x00 should be 0.0"
    assert abs(e4m3[0x38] - 1.0) < 1e-6, f"E4M3 index 0x38 should be 1.0, got {e4m3[0x38]}"
    assert abs(e4m3[0x7E] - 448.0) < 1e-6, f"E4M3 index 0x7E should be 448.0 (max), got {e4m3[0x7E]}"

    # E4M3 negative values
    assert abs(e4m3[0x80] - 0.0) < 1e-10, f"E4M3 index 0x80 should be -0.0, got {e4m3[0x80]}"
    assert abs(e4m3[0xB8] - (-1.0)) < 1e-6, f"E4M3 index 0xB8 should be -1.0, got {e4m3[0xB8]}"
    assert abs(e4m3[0xFE] - (-448.0)) < 1e-6, f"E4M3 index 0xFE should be -448.0 (min), got {e4m3[0xFE]}"

    # E5M2 positive values
    assert e5m2[0] == 0.0, "E5M2 index 0x00 should be 0.0"
    assert abs(e5m2[0x3C] - 1.0) < 1e-6, f"E5M2 index 0x3C should be 1.0, got {e5m2[0x3C]}"
    assert abs(e5m2[0x7B] - 57344.0) < 1e-6, f"E5M2 index 0x7B should be 57344.0 (max finite), got {e5m2[0x7B]}"

    # E5M2 special values
    assert math.isinf(e5m2[0x7C]), f"E5M2 index 0x7C should be +inf, got {e5m2[0x7C]}"
    assert math.isnan(e5m2[0x7D]), f"E5M2 index 0x7D should be NaN, got {e5m2[0x7D]}"
    assert math.isinf(e5m2[0xFC]) and e5m2[0xFC] < 0, f"E5M2 index 0xFC should be -inf, got {e5m2[0xFC]}"

    print("Note: LUT generation replaces inf→57344.0f, NaN→0.0f for C compatibility.")
    print("      The store path never writes these patterns, so they should never be loaded.")

    # E5M2 negative values
    assert abs(e5m2[0x80] - 0.0) < 1e-10, f"E5M2 index 0x80 should be -0.0, got {e5m2[0x80]}"
    assert abs(e5m2[0xBC] - (-1.0)) < 1e-6, f"E5M2 index 0xBC should be -1.0, got {e5m2[0xBC]}"
    assert abs(e5m2[0xFB] - (-57344.0)) < 1e-6, f"E5M2 index 0xFB should be -57344.0 (min finite), got {e5m2[0xFB]}"

    print("LUT validation passed.")


def main():
    parser = argparse.ArgumentParser(description="Generate FP8 lookup tables")
    parser.add_argument("--backend", choices=["opencl", "cpu"], required=True,
                        help="Target backend: opencl or cpu")
    parser.add_argument("--output", type=Path, required=True,
                        help="Output path for generated header")
    args = parser.parse_args()

    e4m3 = generate_e4m3_lut()
    e5m2 = generate_e5m2_lut()

    validate_tables(e4m3, e5m2)

    is_opencl = args.backend == "opencl"
    generate_header(e4m3, e5m2, is_opencl=is_opencl, output_path=args.output)


if __name__ == "__main__":
    main()
