# src/tests/test_parameter_space.py
"""
Unit tests for ParameterSpace: flow declarations, naming conventions,
and memory layout generation.

Bug-hunting focus:
* The "partial_grad" → "clipped_partial_grad" naming transform must be
  consistent between ParameterFlowConfig.clipped_partial_grad_buffer_name
  and the layout dictionary entry generated by get_all_memory_layouts().
* Every flow's buffer names must actually appear in the layout dict.
* Hidden_activations flow (specialized_reduction=True) must NOT create
  layout entries for partial/clipped/final/adam buffers.
"""
from __future__ import annotations

import numpy as np
import pytest

from src.model_spec import Float32ModelSpec, Float16ModelSpec
from src.parameter_space import ParameterSpace, ParameterFlowConfig
from src.workload_primitives import TilingScheme


# =========================================================================
# 1. ParameterFlowConfig naming consistency
# =========================================================================


class TestParameterFlowConfigNaming:
    """Each flow must generate buffer names following a predictable pattern."""

    def test_standard_flow_names(self) -> None:
        """A non-specialized flow should produce six distinct buffer name fields."""
        ps = ParameterSpace(spec=Float32ModelSpec(
            input_dim=4, hidden_dim=32, output_classes=3,
            num_modules=8, simd_width=4, cache_line_bytes=64,
        ))
        standard_flows = [f for f in ps if not f.specialized_reduction]
        assert len(standard_flows) >= 4, "Expected at least shared_weights, shared_biases, module_weights, module_biases"

        for flow in standard_flows:
            # partial must contain "partial_grad"
            assert "partial_grad" in flow.partial_grad_buffer_name, \
                f"Flow '{flow.name}': partial_grad_buffer_name = '{flow.partial_grad_buffer_name}' lacks 'partial_grad'"
            # clipped must contain "clipped_partial_grad"
            assert "clipped_partial_grad" in flow.clipped_partial_grad_buffer_name, \
                f"Flow '{flow.name}': clipped name = '{flow.clipped_partial_grad_buffer_name}' lacks 'clipped_partial_grad'"
            # summed
            assert flow.summed_grad_buffer_name.startswith("summed_grad_"), \
                f"Flow '{flow.name}': summed = '{flow.summed_grad_buffer_name}'"
            # final
            assert flow.final_grad_buffer_name.startswith("final_grad_"), \
                f"Flow '{flow.name}': final = '{flow.final_grad_buffer_name}'"
            # adam
            assert flow.m1_buffer_name.startswith("m1_"), \
                f"Flow '{flow.name}': m1 = '{flow.m1_buffer_name}'"
            assert flow.m2_buffer_name.startswith("m2_"), \
                f"Flow '{flow.name}': m2 = '{flow.m2_buffer_name}'"

    def test_specialized_flow_has_empty_buffer_names(self) -> None:
        """The hidden_activations flow is specialized and should not have intermediate buffer names."""
        ps = ParameterSpace(spec=Float32ModelSpec(
            input_dim=4, hidden_dim=32, output_classes=3,
            num_modules=8, simd_width=4, cache_line_bytes=64,
        ))
        specialized = [f for f in ps if f.specialized_reduction]
        assert len(specialized) >= 1
        for flow in specialized:
            assert flow.partial_grad_buffer_name == "", f"Expected empty partial for specialized flow '{flow.name}'"
            assert flow.clipped_partial_grad_buffer_name == ""
            assert flow.final_grad_buffer_name == ""
            assert flow.m1_buffer_name == ""
            assert flow.m2_buffer_name == ""
            # But summed should exist
            assert flow.summed_grad_buffer_name != ""

    def test_temperatures_use_temps_grad_name(self) -> None:
        """The temperatures flow uses 'temps' as the grad name, not 'temperatures'."""
        ps = ParameterSpace(spec=Float32ModelSpec(
            input_dim=4, hidden_dim=32, output_classes=3,
            num_modules=8, simd_width=4, cache_line_bytes=64,
        ))
        temp_flow = next(f for f in ps if f.name == "temperatures")
        assert temp_flow.partial_grad_buffer_name == "partial_grad_temps"
        assert temp_flow.clipped_partial_grad_buffer_name == "clipped_partial_grad_temps"
        assert temp_flow.summed_grad_buffer_name == "summed_grad_temps"


# =========================================================================
# 2. Memory layout dictionary — naming consistency with ParameterFlowConfig
# =========================================================================


class TestLayoutDictionaryConsistency:
    """The layout dict keys must match the names generated by ParameterFlowConfig."""

    def _make_tiling(self, spec: Float32ModelSpec) -> TilingScheme:
        return TilingScheme(
            num_module_chunks=(spec.num_modules + 15) // 16,
            num_class_chunks=(spec.output_classes + 15) // 16,
            total_modules=spec.num_modules,
            total_classes=spec.output_classes,
        )

    @pytest.mark.parametrize("batch_size", [32, 150])
    def test_every_flow_buffer_name_exists_in_layouts(self, iris_spec: Float32ModelSpec, batch_size: int) -> None:
        """All non-empty buffer names declared by each flow must be present in the layout dict."""
        ps = ParameterSpace(spec=iris_spec)
        grid = self._make_tiling(iris_spec)
        layouts = ps.get_all_memory_layouts(batch_size=batch_size, grid=grid, num_batch_chunks=4)

        missing = []
        for flow in ps:
            for attr in [
                "param_buffer_name",
                "partial_grad_buffer_name",
                "clipped_partial_grad_buffer_name",
                "summed_grad_buffer_name",
                "final_grad_buffer_name",
                "m1_buffer_name",
                "m2_buffer_name",
            ]:
                name = getattr(flow, attr)
                if name and name not in layouts:
                    missing.append(f"Flow '{flow.name}'.{attr} = '{name}'")

        assert not missing, (
            f"Buffer names declared by ParameterFlowConfig but MISSING in layouts:\n"
            + "\n".join(f"  - {m}" for m in missing)
        )

    def test_clipped_names_match_flow_config_exactly(self, iris_spec: Float32ModelSpec) -> None:
        """
        The `partial_grad_X` → `clipped_partial_grad_X` transform in the layout
        dict must produce keys that exactly match each flow's
        clipped_partial_grad_buffer_name.

        Regression: a prior bug used .replace("partial", "clipped") which
        turned 'partial_grad_X' into 'clipped_grad_X' — missing the 'partial'.
        """
        ps = ParameterSpace(spec=iris_spec)
        grid = self._make_tiling(iris_spec)
        layouts = ps.get_all_memory_layouts(batch_size=150, grid=grid, num_batch_chunks=4)

        for flow in ps:
            if not flow.clipped_partial_grad_buffer_name:
                continue
            expected_name = flow.clipped_partial_grad_buffer_name
            assert expected_name in layouts, (
                f"Flow '{flow.name}': expected layout key '{expected_name}' "
                f"but it is ABSENT.  Layout keys containing 'clipped': "
                f"{[k for k in layouts if 'clipped' in k]}"
            )

    def test_partial_and_clipped_shapes_match(self, iris_spec: Float32ModelSpec) -> None:
        """A clipped buffer must have exactly the same logical shape as its partial precursor."""
        ps = ParameterSpace(spec=iris_spec)
        grid = self._make_tiling(iris_spec)
        layouts = ps.get_all_memory_layouts(batch_size=150, grid=grid, num_batch_chunks=4)

        for flow in ps:
            if not flow.partial_grad_buffer_name or not flow.clipped_partial_grad_buffer_name:
                continue
            partial_layout = layouts[flow.partial_grad_buffer_name]
            clipped_layout = layouts[flow.clipped_partial_grad_buffer_name]
            assert partial_layout.logical_shape == clipped_layout.logical_shape, (
                f"Flow '{flow.name}': partial shape {partial_layout.logical_shape} "
                f"!= clipped shape {clipped_layout.logical_shape}"
            )


# =========================================================================
# 3. Memory layout shapes — dimensionality correctness
# =========================================================================


class TestLayoutShapes:
    """Verify that critical layout shapes are dimensionally self-consistent."""

    def _make_layouts(self, spec, batch_size=150, num_batch_chunks=4):
        ps = ParameterSpace(spec=spec)
        grid = TilingScheme(
            num_module_chunks=(spec.num_modules + 15) // 16,
            num_class_chunks=(spec.output_classes + 15) // 16,
            total_modules=spec.num_modules,
            total_classes=spec.output_classes,
        )
        return ps.get_all_memory_layouts(batch_size=batch_size, grid=grid, num_batch_chunks=num_batch_chunks), grid

    def test_shared_weights_shape(self, iris_spec: Float32ModelSpec) -> None:
        """shared_weights shape must be (padded_hidden_dim, padded_input_dim)."""
        layouts, _ = self._make_layouts(iris_spec)
        sw = layouts["shared_weights"]
        assert sw.logical_shape == (iris_spec.padded_hidden_dim, iris_spec.padded_input_dim)

    def test_module_weights_shape(self, iris_spec: Float32ModelSpec) -> None:
        """module_weights shape must be (num_modules, padded_hidden_dim, padded_class_dim)."""
        layouts, _ = self._make_layouts(iris_spec)
        mw = layouts["module_weights"]
        assert mw.logical_shape == (
            iris_spec.num_modules,
            iris_spec.padded_hidden_dim,
            iris_spec.padded_class_dim,
        )

    def test_adam_state_shapes_match_params(self, iris_spec: Float32ModelSpec) -> None:
        """Optimizer state buffers (m1, m2, summed_grad, final_grad) match the param shape."""
        layouts, _ = self._make_layouts(iris_spec)
        ps = ParameterSpace(spec=iris_spec)

        for flow in ps:
            if flow.specialized_reduction:
                continue
            param_shape = layouts[flow.param_buffer_name].logical_shape
            for buf_name in [flow.summed_grad_buffer_name, flow.final_grad_buffer_name,
                             flow.m1_buffer_name, flow.m2_buffer_name]:
                assert layouts[buf_name].logical_shape == param_shape, (
                    f"Flow '{flow.name}': '{buf_name}' shape {layouts[buf_name].logical_shape} "
                    f"!= param shape {param_shape}"
                )

    def test_partial_grad_module_weights_has_tile_dim(self, iris_spec: Float32ModelSpec) -> None:
        """partial_grad_module_weights must have a leading tile dimension."""
        layouts, grid = self._make_layouts(iris_spec)
        pgmw = layouts["partial_grad_module_weights"]
        assert pgmw.logical_shape[0] == grid.total_tiles, (
            f"First dim {pgmw.logical_shape[0]} != total_tiles {grid.total_tiles}"
        )

    def test_partial_grad_shared_weights_has_chunk_dim(self, iris_spec: Float32ModelSpec) -> None:
        """partial_grad_shared_weights must have a leading batch-chunk dimension."""
        layouts, _ = self._make_layouts(iris_spec, num_batch_chunks=4)
        pgsw = layouts["partial_grad_shared_weights"]
        assert pgsw.logical_shape[0] == 4, f"First dim {pgsw.logical_shape[0]} != num_batch_chunks=4"
        assert pgsw.logical_shape[1] == iris_spec.padded_hidden_dim
        assert pgsw.logical_shape[2] == iris_spec.padded_input_dim

    @pytest.mark.parametrize("spec_name", ["iris", "hydra", "lexicon"])
    def test_final_probs_exists(self, spec_name, iris_spec, hydra_spec, lexicon_spec) -> None:
        """final_probs must be present as a layout key."""
        specs = {"iris": iris_spec, "hydra": hydra_spec, "lexicon": lexicon_spec}
        layouts, _ = self._make_layouts(specs[spec_name])
        assert "final_probs" in layouts, f"'final_probs' missing from layout dict for {spec_name}"

    def test_final_loss_exists(self, iris_spec: Float32ModelSpec) -> None:
        """final_loss must be present as a layout key."""
        layouts, _ = self._make_layouts(iris_spec)
        assert "final_loss" in layouts

    def test_permuted_grad_h_shape(self, iris_spec: Float32ModelSpec) -> None:
        """permuted_grad_h must be (batch*padded_hidden, padded_module_dim)."""
        layouts, _ = self._make_layouts(iris_spec)
        p = layouts["permuted_grad_h"]
        assert p.logical_shape == (
            150 * iris_spec.padded_hidden_dim,
            iris_spec.padded_module_dim,
        )


# =========================================================================
# 4. Hydra / Lexicon stress tests
# =========================================================================


class TestStressScenarios:
    """Verify that large-scale configs don't break naming or shape contracts."""

    @pytest.mark.parametrize("spec_fixture,batch_size", [
        ("hydra_spec", 32),
        ("lexicon_spec", 64),
    ])
    def test_all_flow_names_in_layouts(self, spec_fixture, batch_size, request) -> None:
        spec = request.getfixturevalue(spec_fixture)
        ps = ParameterSpace(spec=spec)
        grid = TilingScheme(
            num_module_chunks=(spec.num_modules + 15) // 16,
            num_class_chunks=(spec.output_classes + 15) // 16,
            total_modules=spec.num_modules,
            total_classes=spec.output_classes,
        )
        layouts = ps.get_all_memory_layouts(batch_size=batch_size, grid=grid, num_batch_chunks=4)

        for flow in ps:
            for attr in [
                "param_buffer_name",
                "partial_grad_buffer_name",
                "clipped_partial_grad_buffer_name",
                "summed_grad_buffer_name",
                "final_grad_buffer_name",
                "m1_buffer_name",
                "m2_buffer_name",
            ]:
                name = getattr(flow, attr)
                if name:
                    assert name in layouts, f"Missing layout for {spec_fixture} flow '{flow.name}'.{attr} = '{name}'"
