"""ctypes Structure definitions mirroring cpu_kernels.h argument structs (ADR-015).

Field order MUST exactly match the C struct field order in cpu_kernels.h.
Layout verification via _verify_layouts() catches size mismatches at load time.

Multi-precision support (ADR-008, ADR-023, ADR-024): the CPU library exports
11 three-axis precision variants using the suffix s{s}c{c}x{x}
(STORAGE_T × COMPUTE_T × STATE_T).  ``make_precision_types()``
creates the ctypes Structure classes for a given precision suffix.

Module-level names (``ForwardPassArgs``, ``c_real_p``, etc.) alias the
s32c32x32 variants for backward compatibility.
"""
from __future__ import annotations

import ctypes
from ctypes import (
    POINTER,
    Structure,
    c_double,
    c_float,
    c_int32,
    c_uint16,
    c_uint32,
    c_void_p,
)

c_float_p = POINTER(c_float)
c_uint_p = POINTER(c_uint32)
c_int_p = POINTER(c_int32)
c_uint8_p = POINTER(ctypes.c_uint8)

# Three-axis precision suffixes s{storage}c{compute}x{state} (ADR-024 §4.1)
PRECISION_SUFFIXES = (
    "s16c16x32", "s16c16x64",
    "s16c32x32", "s16c32x64",
    "s16c64x64",
    "s32c32x32", "s32c32x64",
    "s32c64x64",
    "s64c64x64",
    # FP8 E4M3 storage (ADR-025 §5.3)
    "s8e4c32x32", "s8e4c32x64", "s8e4c64x64",
    # FP8 E5M2 storage (ADR-025 §5.3)
    "s8e5c32x32", "s8e5c32x64", "s8e5c64x64",
)

# FP8 variants with FP16 compute — conditionally compiled if _Float16 available.
# These are loaded dynamically from the generated _fp8_variants module.
FP8_FP16_PRECISION_SUFFIXES: tuple[str, ...] = ()
try:
    from ._fp8_variants import AVAILABLE_FP8_VARIANTS, HAS_FLOAT16 as _HAS_FLOAT16  # type: ignore[reportMissingImports]  # generated by Meson
    if _HAS_FLOAT16:
        FP8_FP16_PRECISION_SUFFIXES = (
            "s8e4c16x32", "s8e4c16x64",
            "s8e5c16x32", "s8e5c16x64",
        )
except ImportError:
    pass

# All suffixes including conditional FP8+FP16 compute variants
ALL_PRECISION_SUFFIXES = PRECISION_SUFFIXES + FP8_FP16_PRECISION_SUFFIXES

# Two-axis aliases for backward compatibility (old suffix → new suffix).
_SUFFIX_ALIASES = {"s32x32": "s32c32x32", "s16x32": "s16c32x32"}

# (c_storage, c_storage_p, c_compute, c_compute_p, c_state, c_state_p) per suffix.
# FP16 uses c_uint16 because ctypes has no _Float16; both are 2-byte types.
PRECISION_C_TYPES: dict[str, tuple[type, type, type, type, type, type]] = {
    "s16c16x32": (c_uint16, POINTER(c_uint16), c_uint16, POINTER(c_uint16), c_float, POINTER(c_float)),
    "s16c16x64": (c_uint16, POINTER(c_uint16), c_uint16, POINTER(c_uint16), c_double, POINTER(c_double)),
    "s16c32x32": (c_uint16, POINTER(c_uint16), c_float, POINTER(c_float), c_float, POINTER(c_float)),
    "s16c32x64": (c_uint16, POINTER(c_uint16), c_float, POINTER(c_float), c_double, POINTER(c_double)),
    "s16c64x64": (c_uint16, POINTER(c_uint16), c_double, POINTER(c_double), c_double, POINTER(c_double)),
    "s32c32x32": (c_float, POINTER(c_float), c_float, POINTER(c_float), c_float, POINTER(c_float)),
    "s32c32x64": (c_float, POINTER(c_float), c_float, POINTER(c_float), c_double, POINTER(c_double)),
    "s32c64x64": (c_float, POINTER(c_float), c_double, POINTER(c_double), c_double, POINTER(c_double)),
    "s64c64x64": (c_double, POINTER(c_double), c_double, POINTER(c_double), c_double, POINTER(c_double)),
    # FP8 E4M3 storage — cpu_fp8_e4m3 is a struct wrapping uint8_t (ADR-025 §5.1)
    "s8e4c32x32": (ctypes.c_uint8, c_uint8_p, c_float, POINTER(c_float), c_float, POINTER(c_float)),
    "s8e4c32x64": (ctypes.c_uint8, c_uint8_p, c_float, POINTER(c_float), c_double, POINTER(c_double)),
    "s8e4c64x64": (ctypes.c_uint8, c_uint8_p, c_double, POINTER(c_double), c_double, POINTER(c_double)),
    # FP8 E5M2 storage — cpu_fp8_e5m2 is a struct wrapping uint8_t (ADR-025 §5.1)
    "s8e5c32x32": (ctypes.c_uint8, c_uint8_p, c_float, POINTER(c_float), c_float, POINTER(c_float)),
    "s8e5c32x64": (ctypes.c_uint8, c_uint8_p, c_float, POINTER(c_float), c_double, POINTER(c_double)),
    "s8e5c64x64": (ctypes.c_uint8, c_uint8_p, c_double, POINTER(c_double), c_double, POINTER(c_double)),
    # FP8 FP16 compute variants (conditional on _Float16)
    "s8e4c16x32": (ctypes.c_uint8, c_uint8_p, c_uint16, POINTER(c_uint16), c_float, POINTER(c_float)),
    "s8e4c16x64": (ctypes.c_uint8, c_uint8_p, c_uint16, POINTER(c_uint16), c_double, POINTER(c_double)),
    "s8e5c16x32": (ctypes.c_uint8, c_uint8_p, c_uint16, POINTER(c_uint16), c_float, POINTER(c_float)),
    "s8e5c16x64": (ctypes.c_uint8, c_uint8_p, c_uint16, POINTER(c_uint16), c_double, POINTER(c_double)),
}

# Base names for struct-size getter exports (suffix appended per precision).
_LAYOUT_CHECK_BASE_NAMES: list[tuple[str, str]] = [
    ("get_struct_size_forward_pass_args", "ForwardPassArgs"),
    ("get_struct_size_render_logits_args", "RenderLogitsArgs"),
    ("get_struct_size_cce_chunk_args", "CceChunkArgs"),
    ("get_struct_size_bce_chunk_args", "BceChunkArgs"),
    ("get_struct_size_module_param_grads_args", "ModuleParamGradsArgs"),
    ("get_struct_size_backprop_to_hidden_args", "BackpropToHiddenArgs"),
    ("get_struct_size_temp_gradients_args", "TempGradientsArgs"),
    ("get_struct_size_clip_partials_args", "ClipPartialsArgs"),
    ("get_struct_size_gather_permute_args", "GatherPermuteArgs"),
    ("get_struct_size_reduction_tree_plan", "ReductionTreePlanFFI"),
    ("get_struct_size_reduction_tree_plan_compute_entry", "ReductionTreePlanComputeEntryFFI"),
    ("get_struct_size_stabilize_reduce_args", "StabilizeReduceArgs"),
    ("get_struct_size_clip_intermediate_args", "ClipIntermediateArgs"),
    ("get_struct_size_backprop_shared_weights_args", "BackpropSharedWeightsArgs"),
    ("get_struct_size_backprop_shared_biases_args", "BackpropSharedBiasesArgs"),
    ("get_struct_size_clip_shared_grads_args", "ClipSharedGradsArgs"),
    ("get_struct_size_normalize_gradients_args", "NormalizeGradientsArgs"),
    ("get_struct_size_adam_update_args", "AdamUpdateArgs"),
    ("get_struct_size_clamp_temperatures_args", "ClampTemperaturesArgs"),
]


def make_precision_types(
    suffix: str,
) -> tuple[dict[str, type], list[tuple[str, type]]]:
    """Create all ctypes Structure classes for a single precision.

    Returns ``(structs_dict, layout_checks)`` where:
      - *structs_dict*: ``{"ForwardPassArgs": <class>, ...}``
      - *layout_checks*: ``[("get_struct_size_forward_pass_args_s32c32x32", <class>), ...]``

    Uses three-axis type mapping (ADR-024 §4):
      - c_storage_p: input, mask, activations, logits, gradients, partials
      - c_compute_p: summed_grad, final_grad, loss, output, intermediate_grad
      - c_state_p: weights, biases, temps, optimizer state (parameters, m1, m2)
    """
    c_storage, c_storage_p, c_compute, c_compute_p, c_state, c_state_p = PRECISION_C_TYPES[suffix]

    def _s(name: str, fields: list) -> type:
        """Create a named Structure subclass."""
        return type(f"{name}_{suffix}", (Structure,), {"_fields_": fields})

    structs: dict[str, type] = {}

    # --- Act Phase ---

    structs["ForwardPassArgs"] = _s("ForwardPassArgs", [
        ("input", c_storage_p),
        ("sample_mask", c_storage_p),
        ("weights_shared_simd_major", c_state_p),
        ("biases_shared", c_state_p),
        ("hidden_activations", c_storage_p),
        ("hidden_mask", c_storage_p),
        ("batch_chunk_offset", c_uint32),
        ("batch_chunk_count", c_uint32),
        ("total_batch_count", c_uint32),
        ("padded_input_count", c_uint32),
        ("padded_hidden_count", c_uint32),
    ])

    structs["RenderLogitsArgs"] = _s("RenderLogitsArgs", [
        ("hidden_activations", c_storage_p),
        ("hidden_mask", c_storage_p),
        ("weights_module", c_state_p),
        ("biases_module", c_state_p),
        ("logits", c_storage_p),
        ("batch_chunk_offset", c_uint32),
        ("batch_chunk_count", c_uint32),
        ("module_chunk_offset", c_uint32),
        ("module_chunk_count", c_uint32),
        ("class_chunk_offset", c_uint32),
        ("class_chunk_count", c_uint32),
        ("total_batch_count", c_uint32),
        ("hidden_count", c_uint32),
        ("padded_hidden_count", c_uint32),
        ("total_output_class_count", c_uint32),
        ("padded_total_output_class_count", c_uint32),
        ("total_modules_count", c_uint32),
    ])

    # --- Learn Phase A: Loss & Gradient Production ---

    structs["CceChunkArgs"] = _s("CceChunkArgs", [
        ("logits", c_storage_p),
        ("temps", c_state_p),
        ("targets", c_int_p),
        ("sample_mask", c_storage_p),
        ("partial_probs", c_storage_p),
        ("final_loss", c_compute_p),  # compute output
        ("flat_tile_index", c_uint32),
        ("num_class_chunks", c_uint32),
        ("classes_per_chunk", c_uint32),
        ("modules_per_chunk", c_uint32),
        ("total_batch_count", c_uint32),
        ("total_output_class_count", c_uint32),
        ("padded_total_output_class_count", c_uint32),
        ("total_modules_count", c_uint32),
        ("total_tile_count", c_uint32),
    ])

    structs["BceChunkArgs"] = _s("BceChunkArgs", [
        ("logits", c_storage_p),
        ("temps", c_state_p),
        ("targets", c_storage_p),  # BCE targets in storage dtype
        ("sample_mask", c_storage_p),
        ("partial_probs", c_storage_p),
        ("partial_loss", c_storage_p),  # BCE partial loss in storage dtype
        ("flat_tile_index", c_uint32),
        ("num_class_chunks", c_uint32),
        ("classes_per_chunk", c_uint32),
        ("modules_per_chunk", c_uint32),
        ("total_batch_count", c_uint32),
        ("total_output_class_count", c_uint32),
        ("padded_total_output_class_count", c_uint32),
        ("total_modules_count", c_uint32),
        ("total_tile_count", c_uint32),
    ])

    structs["ModuleParamGradsArgs"] = _s("ModuleParamGradsArgs", [
        ("hidden_activations", c_storage_p),
        ("partial_probs", c_storage_p),
        ("targets", c_void_p),
        ("sample_mask", c_storage_p),
        ("partial_grad_weights_module", c_storage_p),
        ("partial_grad_biases_module", c_storage_p),
        ("problem_type", c_uint32),
        ("flat_tile_index", c_uint32),
        ("batch_chunk_offset", c_uint32),
        ("batch_chunk_count", c_uint32),
        ("num_class_chunks", c_uint32),
        ("classes_per_chunk", c_uint32),
        ("modules_per_chunk", c_uint32),
        ("total_batch_count", c_uint32),
        ("hidden_count", c_uint32),
        ("padded_hidden_count", c_uint32),
        ("total_output_class_count", c_uint32),
        ("padded_total_output_class_count", c_uint32),
        ("total_modules_count", c_uint32),
        ("total_tile_count", c_uint32),
    ])

    # --- Learn Phase B: Processing ---

    structs["BackpropToHiddenArgs"] = _s("BackpropToHiddenArgs", [
        ("partial_probs", c_storage_p),
        ("targets", c_void_p),
        ("sample_mask", c_storage_p),
        ("weights_module", c_state_p),
        ("partial_grad_hidden_activations_aos", c_storage_p),
        ("problem_type", c_uint32),
        ("flat_tile_index", c_uint32),
        ("num_class_chunks", c_uint32),
        ("classes_per_chunk", c_uint32),
        ("modules_per_chunk", c_uint32),
        ("total_batch_count", c_uint32),
        ("hidden_count", c_uint32),
        ("padded_hidden_count", c_uint32),
        ("total_output_class_count", c_uint32),
        ("padded_total_output_class_count", c_uint32),
        ("total_modules_count", c_uint32),
        ("total_tile_count", c_uint32),
    ])

    structs["TempGradientsArgs"] = _s("TempGradientsArgs", [
        ("logits", c_storage_p),
        ("partial_probs", c_storage_p),
        ("targets", c_void_p),
        ("sample_mask", c_storage_p),
        ("temps", c_state_p),
        ("partial_grad_temps", c_storage_p),
        ("problem_type", c_uint32),
        ("flat_tile_index", c_uint32),
        ("num_class_chunks", c_uint32),
        ("classes_per_chunk", c_uint32),
        ("modules_per_chunk", c_uint32),
        ("total_batch_count", c_uint32),
        ("total_output_class_count", c_uint32),
        ("padded_total_output_class_count", c_uint32),
        ("total_modules_count", c_uint32),
        ("total_tile_count", c_uint32),
    ])

    structs["ClipPartialsArgs"] = _s("ClipPartialsArgs", [
        ("partial_grad_weights_module", c_storage_p),
        ("partial_grad_biases_module", c_storage_p),
        ("partial_grad_temps", c_storage_p),
        ("partial_grad_hidden_activations_aos", c_storage_p),
        ("clipping_threshold_per_item", c_storage_p),
        ("clipped_partial_grad_weights_module", c_storage_p),
        ("clipped_partial_grad_biases_module", c_storage_p),
        ("clipped_partial_grad_temps", c_storage_p),
        ("clipped_partial_grad_hidden_activations_aos", c_storage_p),
        ("use_per_item_norm", c_uint32),
        ("clipping_threshold_t_pre", c_float),  # scalar compute param
        ("epsilon", c_float),
        ("flat_tile_index", c_uint32),
        ("num_class_chunks", c_uint32),
        ("classes_per_chunk", c_uint32),
        ("modules_per_chunk", c_uint32),
        ("total_batch_count", c_uint32),
        ("padded_hidden_count", c_uint32),
        ("padded_total_output_class_count", c_uint32),
        ("total_tile_count", c_uint32),
    ])

    # --- Learn Phase C: Reduction ---

    structs["GatherPermuteArgs"] = _s("GatherPermuteArgs", [
        ("clipped_partial_grad_hidden_activations_aos", c_storage_p),
        ("clipped_grad_hidden_activations_permuted_soa", c_storage_p),
        ("total_batch_count", c_uint32),
        ("hidden_count", c_uint32),
        ("padded_hidden_count", c_uint32),
        ("total_modules_count", c_uint32),
        ("padded_total_modules_count", c_uint32),
        ("num_module_chunks", c_uint32),
        ("modules_per_chunk", c_uint32),
        ("num_class_chunks", c_uint32),
        ("total_tile_count", c_uint32),
    ])

    structs["ReductionTreePlanFFI"] = _s("ReductionTreePlanFFI", [
        ("partial_collection", c_storage_p),
        ("offset_lists_flat", c_uint_p),
        ("stage_offsets_into_list", c_uint_p),
        ("stage_fan_in", c_uint_p),
        ("stage_node_counts", c_uint_p),
        ("staging_buffer_0", c_storage_p),
        ("staging_buffer_1", c_storage_p),
        ("output", c_compute_p),  # compute output
        ("partial_width", c_uint32),
        ("num_stages", c_uint32),
        ("t_algorithmic", c_compute),
        ("lambda_", c_compute),
        ("fp_max", c_compute),
        ("epsilon", c_compute),
    ])

    # ADR-026: Compute-entry variant for compute-role source buffers
    structs["ReductionTreePlanComputeEntryFFI"] = _s("ReductionTreePlanComputeEntryFFI", [
        ("partial_collection", c_compute_p),  # compute-role input
        ("offset_lists_flat", c_uint_p),
        ("stage_offsets_into_list", c_uint_p),
        ("stage_fan_in", c_uint_p),
        ("stage_node_counts", c_uint_p),
        ("staging_buffer_0", c_compute_p),  # compute-role staging
        ("staging_buffer_1", c_compute_p),  # compute-role staging
        ("output", c_compute_p),
        ("partial_width", c_uint32),
        ("num_stages", c_uint32),
        ("t_algorithmic", c_compute),
        ("lambda_", c_compute),
        ("fp_max", c_compute),
        ("epsilon", c_compute),
    ])

    structs["StabilizeReduceArgs"] = _s("StabilizeReduceArgs", [
        ("grad_hidden_activations_permuted_soa", c_storage_p),
        ("summed_grad_hidden_activations", c_compute_p),  # compute output
        ("fp_max", c_compute),
        ("policy_t_algorithmic", c_compute),
        ("policy_lambda", c_compute),
        ("policy_max_k", c_uint32),
        ("epsilon", c_compute),
        ("total_batch_count", c_uint32),
        ("padded_hidden_count", c_uint32),
        ("total_modules_count", c_uint32),
        ("padded_total_modules_count", c_uint32),
    ])

    structs["ClipIntermediateArgs"] = _s("ClipIntermediateArgs", [
        ("intermediate_grad", c_compute_p),  # compute intermediate
        ("clipping_threshold_t_j", c_compute),
        ("epsilon", c_compute),
        ("parameter_count", c_uint32),
    ])

    # --- Learn Phase D: Streaming Backprop ---

    structs["BackpropSharedWeightsArgs"] = _s("BackpropSharedWeightsArgs", [
        ("input", c_storage_p),
        ("hidden_activations", c_storage_p),
        ("summed_grad_hidden_activations", c_compute_p),  # compute output
        ("sample_mask", c_storage_p),
        ("partial_grad_weights_shared", c_storage_p),
        ("batch_chunk_offset", c_uint32),
        ("batch_chunk_count", c_uint32),
        ("batch_chunk_index", c_uint32),
        ("total_batch_count", c_uint32),
        ("num_batch_chunks_count", c_uint32),
        ("padded_input_count", c_uint32),
        ("padded_hidden_count", c_uint32),
        ("final_grad_hidden_total_element_count", c_uint32),
    ])

    structs["BackpropSharedBiasesArgs"] = _s("BackpropSharedBiasesArgs", [
        ("hidden_activations", c_storage_p),
        ("summed_grad_hidden_activations", c_compute_p),  # compute output
        ("sample_mask", c_storage_p),
        ("partial_grad_biases_shared", c_storage_p),
        ("batch_chunk_offset", c_uint32),
        ("batch_chunk_count", c_uint32),
        ("batch_chunk_index", c_uint32),
        ("total_batch_count", c_uint32),
        ("num_batch_chunks_count", c_uint32),
        ("padded_hidden_count", c_uint32),
        ("final_grad_hidden_total_element_count", c_uint32),
    ])

    structs["ClipSharedGradsArgs"] = _s("ClipSharedGradsArgs", [
        ("partial_grad_weights_shared", c_storage_p),
        ("partial_grad_biases_shared", c_storage_p),
        ("clipped_partial_grad_weights_shared", c_storage_p),
        ("clipped_partial_grad_biases_shared", c_storage_p),
        ("clipping_threshold_t_pre", c_float),
        ("epsilon", c_float),
        ("weights_parameter_count", c_uint32),
        ("biases_parameter_count", c_uint32),
        ("weights_write_offset_elements", c_uint32),
        ("biases_write_offset_elements", c_uint32),
        ("num_batch_chunks", c_uint32),
    ])

    # --- Update Phase ---

    structs["NormalizeGradientsArgs"] = _s("NormalizeGradientsArgs", [
        ("summed_grad", c_compute_p),  # compute
        ("final_grad", c_compute_p),   # compute
        ("effective_batch_size", c_compute),
        ("epsilon", c_compute),
        ("parameter_count", c_uint32),
    ])

    structs["AdamUpdateArgs"] = _s("AdamUpdateArgs", [
        ("final_grad", c_compute_p),   # compute
        ("parameters", c_state_p),
        ("m1", c_state_p),
        ("m2", c_state_p),
        ("learning_rate", c_compute),
        ("beta1_pow_t", c_compute),
        ("beta2_pow_t", c_compute),
        ("beta1", c_compute),
        ("beta2", c_compute),
        ("epsilon", c_compute),
        ("parameter_count", c_uint32),
    ])

    structs["ClampTemperaturesArgs"] = _s("ClampTemperaturesArgs", [
        ("temperatures", c_state_p),
        ("min_value", c_compute),
        ("max_value", c_compute),
        ("total_modules_count", c_uint32),
    ])

    # Build layout checks with suffixed getter names
    layout_checks = [
        (f"{base_name}_{suffix}", structs[struct_key])
        for base_name, struct_key in _LAYOUT_CHECK_BASE_NAMES
    ]

    return structs, layout_checks


# --- Pre-built precision maps ---

PRECISION_STRUCTS: dict[str, dict[str, type]] = {}
PRECISION_LAYOUT_CHECKS: dict[str, list[tuple[str, type]]] = {}

_sfx, _structs, _checks = "", PRECISION_STRUCTS, PRECISION_LAYOUT_CHECKS
for _sfx in ALL_PRECISION_SUFFIXES:
    _structs, _checks = make_precision_types(_sfx)
    PRECISION_STRUCTS[_sfx] = _structs
    PRECISION_LAYOUT_CHECKS[_sfx] = _checks

del _sfx, _structs, _checks

# --- Backward-compatible module-level aliases (s32c32x32 = pure FP32) ---

c_real: type = c_float
c_real_p: type = POINTER(c_float)
REAL_SIZE_BYTES: int = ctypes.sizeof(c_float)

_DEFAULT_SUFFIX = "s32c32x32"

ForwardPassArgs = PRECISION_STRUCTS[_DEFAULT_SUFFIX]["ForwardPassArgs"]
RenderLogitsArgs = PRECISION_STRUCTS[_DEFAULT_SUFFIX]["RenderLogitsArgs"]
CceChunkArgs = PRECISION_STRUCTS[_DEFAULT_SUFFIX]["CceChunkArgs"]
BceChunkArgs = PRECISION_STRUCTS[_DEFAULT_SUFFIX]["BceChunkArgs"]
ModuleParamGradsArgs = PRECISION_STRUCTS[_DEFAULT_SUFFIX]["ModuleParamGradsArgs"]
BackpropToHiddenArgs = PRECISION_STRUCTS[_DEFAULT_SUFFIX]["BackpropToHiddenArgs"]
TempGradientsArgs = PRECISION_STRUCTS[_DEFAULT_SUFFIX]["TempGradientsArgs"]
ClipPartialsArgs = PRECISION_STRUCTS[_DEFAULT_SUFFIX]["ClipPartialsArgs"]
GatherPermuteArgs = PRECISION_STRUCTS[_DEFAULT_SUFFIX]["GatherPermuteArgs"]
ReductionTreePlanFFI = PRECISION_STRUCTS[_DEFAULT_SUFFIX]["ReductionTreePlanFFI"]
StabilizeReduceArgs = PRECISION_STRUCTS[_DEFAULT_SUFFIX]["StabilizeReduceArgs"]
ClipIntermediateArgs = PRECISION_STRUCTS[_DEFAULT_SUFFIX]["ClipIntermediateArgs"]
BackpropSharedWeightsArgs = PRECISION_STRUCTS[_DEFAULT_SUFFIX]["BackpropSharedWeightsArgs"]
BackpropSharedBiasesArgs = PRECISION_STRUCTS[_DEFAULT_SUFFIX]["BackpropSharedBiasesArgs"]
ClipSharedGradsArgs = PRECISION_STRUCTS[_DEFAULT_SUFFIX]["ClipSharedGradsArgs"]
NormalizeGradientsArgs = PRECISION_STRUCTS[_DEFAULT_SUFFIX]["NormalizeGradientsArgs"]
AdamUpdateArgs = PRECISION_STRUCTS[_DEFAULT_SUFFIX]["AdamUpdateArgs"]
ClampTemperaturesArgs = PRECISION_STRUCTS[_DEFAULT_SUFFIX]["ClampTemperaturesArgs"]

# Backward-compatible layout checks
LAYOUT_CHECKS: list[tuple[str, type]] = PRECISION_LAYOUT_CHECKS[_DEFAULT_SUFFIX]

# Two-axis suffix aliases for callers that haven't migrated yet
_old = _new = ""
for _old, _new in _SUFFIX_ALIASES.items():
    PRECISION_STRUCTS[_old] = PRECISION_STRUCTS[_new]
    PRECISION_LAYOUT_CHECKS[_old] = PRECISION_LAYOUT_CHECKS[_new]
del _old, _new
