/* cpu_fp8.h — FP8 representation and conversion for CPU backend
 * ADR-025 §5.1–5.2
 *
 * Provides conversions to/from:
 *   - _Float16 (FP16 compute) — requires C23 / compiler support
 *   - float (FP32 compute)
 *   - double (FP64 compute)
 */

#ifndef CPU_FP8_H
#define CPU_FP8_H

#include <stdint.h>
#include <stdbool.h>
#include <string.h>  /* for memcpy (strict aliasing compliance) */
#include <math.h>
#include <float.h>   /* for FLT_MAX etc. */

/* --- FP8 Storage Types (ADR-025 §5.1) ---
 * Struct wrappers prevent accidental arithmetic on raw bits.
 */

typedef struct { uint8_t bits; } cpu_fp8_e4m3;
typedef struct { uint8_t bits; } cpu_fp8_e5m2;

/* Defense-in-depth (CONTRACT Article 1.4b): Buffer pointer arithmetic assumes sizeof == 1 */
_Static_assert(sizeof(cpu_fp8_e4m3) == 1, "FP8 E4M3 wrapper must be 1 byte");
_Static_assert(sizeof(cpu_fp8_e5m2) == 1, "FP8 E5M2 wrapper must be 1 byte");

/* --- E4M3 Constants ---
 * sign(1) + exp(4) + mantissa(3), bias=7, max=448, no inf/nan
 */
#define E4M3_BIAS 7
#define E4M3_MANTISSA_BITS 3
#define E4M3_MAX_VAL 448.0f
#define E4M3_MIN_SUBNORMAL 0.001953125f  /* 2^-9 */

/* --- E5M2 Constants ---
 * sign(1) + exp(5) + mantissa(2), bias=15, max=57344
 * Unlike E4M3fn, E5M2 has IEEE-like inf/NaN (exponent 0x1F).
 * The store path saturates to max finite (0x7B/0xFB), never writing inf/NaN patterns.
 */
#define E5M2_BIAS 15
#define E5M2_MANTISSA_BITS 2
#define E5M2_MAX_VAL 57344.0f
#define E5M2_MIN_SUBNORMAL 0.0000152587890625f  /* 2^-16, exact */

/* --- Include generated lookup tables (ADR-025 §6.1) ---
 * Generated by: python scripts/generate_fp8_lut.py
 * Contains: cpu_fp8_e4m3_to_float_lut[256], cpu_fp8_e5m2_to_float_lut[256]
 */
#include "cpu_fp8_lut.gen.h"

/* --- E4M3 Conversion Functions (ADR-025 §5.2) --- */

static inline float cpu_fp8_e4m3_to_float(cpu_fp8_e4m3 val) {
    return cpu_fp8_e4m3_to_float_lut[val.bits];
}

static inline double cpu_fp8_e4m3_to_double(cpu_fp8_e4m3 val) {
    return (double)cpu_fp8_e4m3_to_float_lut[val.bits];
}

/* FP16 conversion — guarded by _Float16 availability
 * Detection strategy: Use Meson-emitted -DHAS_FLOAT16=1 (see Step 9C.4) as the
 * single source of truth.  Meson's cc.compiles() test already verified that the
 * compiler accepts _Float16 with arithmetic; duplicating that check in a header
 * guard via __FLT16_MAX__ risks a mismatch (e.g., __FLT16_MAX__ can be defined
 * even when the linker lacks soft-float routines for _Float16 on some targets).
 *
 * Fallback: If this header is included outside the Meson build (e.g., unit-test
 * harness that compiles directly), HAS_FLOAT16 won't be defined and the FP16
 * conversion functions will be excluded — which is the safe default.
 */
#if defined(HAS_FLOAT16) && HAS_FLOAT16
static inline _Float16 cpu_fp8_e4m3_to_half(cpu_fp8_e4m3 val) {
    return (_Float16)cpu_fp8_e4m3_to_float_lut[val.bits];
}
#endif

static inline cpu_fp8_e4m3 cpu_float_to_fp8_e4m3(float val) {
    cpu_fp8_e4m3 result;

    /* Handle special cases */
    if (isnan(val)) {
        /* E4M3 has no infinities but does have 2 NaN patterns (0x7F, 0xFF).
         * The store path never writes NaN; we map NaN→zero defensively.
         *
         * We map NaN→zero rather than NaN→max because:
         * 1. NaN in gradients typically indicates upstream numerical instability
         *    that should be caught before reaching FP8 conversion.
         * 2. Zero gradients produce no parameter update ("safe" failure mode),
         *    whereas max-value gradients could cause divergence.
         * 3. This matches ml_dtypes.float8_e4m3fn behavior.
         *
         * If fail-fast NaN propagation is desired, check for NaN in host code
         * before invoking CPU kernels. */
        result.bits = 0;
        return result;
    }

    /* Extract sign via bit pattern (strict-aliasing-safe) */
    uint32_t fbits;
    memcpy(&fbits, &val, sizeof(fbits));
    uint32_t sign = (fbits >> 31) & 1;
    float absval = fabsf(val);

    /* Saturation: >= is intentional. 0x7E encodes exactly 448.0, so absval == MAX_VAL
     * short-circuits to the same result the rounding path would produce. */
    if (absval >= E4M3_MAX_VAL) {
        result.bits = (uint8_t)((sign << 7) | 0x7E);  /* Max magnitude */
        return result;
    }

    /* Underflow to zero */
    if (absval < E4M3_MIN_SUBNORMAL * 0.5f) {
        result.bits = (uint8_t)(sign << 7);  /* Signed zero */
        return result;
    }

    /* Extract FP32 exponent and mantissa */
    int exp32 = (int)((fbits >> 23) & 0xFF) - 127;  /* Unbiased exponent */
    uint32_t mant32 = fbits & 0x7FFFFFu;             /* 23-bit mantissa */

    /* Compute FP8 exponent */
    int exp8 = exp32 + E4M3_BIAS;

    /* Handle subnormals */
    if (exp8 <= 0) {
        /* Subnormal in E4M3 */
        int shift = 1 - exp8;
        if (shift >= 24) {
            result.bits = (uint8_t)(sign << 7);  /* Underflow to zero (shift >= 24 is UB) */
            return result;
        }
        mant32 = (mant32 | 0x800000u) >> shift;  /* Denormalize */
        exp8 = 0;
    } else if (exp8 >= 15) {
        /* Overflow — should not reach here due to saturation above */
        result.bits = (uint8_t)((sign << 7) | 0x7E);
        return result;
    }

    /* Round mantissa to 3 bits (round-to-nearest-even) */
    uint32_t round_bit = (mant32 >> 19) & 1;
    uint32_t sticky = mant32 & ((1u << 19) - 1);
    uint32_t mant8 = mant32 >> 20;
    if (round_bit && (sticky || (mant8 & 1))) {
        mant8++;
    }
    if (mant8 >= 8) {
        mant8 = 0;
        exp8++;
        if (exp8 >= 15) {
            result.bits = (uint8_t)((sign << 7) | 0x7E);  /* Overflow to max */
            return result;
        }
    }

    result.bits = (uint8_t)((sign << 7) | ((uint32_t)exp8 << 3) | (mant8 & 0x7u));
    return result;
}

static inline cpu_fp8_e4m3 cpu_double_to_fp8_e4m3(double val) {
    /* Defense-in-depth: clamp before double→float narrowing to prevent UB
     * (C99 §6.3.1.5: double→float overflow is undefined behavior).
     * Pre-scaling (Phase 9E) ensures values are in FP8 range ⊂ FP32 range,
     * so this clamp is redundant under correct operation. Consistent with
     * the OpenCL (Step 9B.3) and Vulkan (Step 9D.2) backends. */
    if (val > (double)FLT_MAX) val = (double)FLT_MAX;
    if (val < -(double)FLT_MAX) val = -(double)FLT_MAX;
    return cpu_float_to_fp8_e4m3((float)val);
}

/* FP16 conversion — guarded by _Float16 availability */
#if defined(HAS_FLOAT16) && HAS_FLOAT16
static inline cpu_fp8_e4m3 cpu_half_to_fp8_e4m3(_Float16 val) {
    return cpu_float_to_fp8_e4m3((float)val);
}
#endif

/* --- E5M2 Conversion Functions (ADR-025 §5.2) --- */

static inline float cpu_fp8_e5m2_to_float(cpu_fp8_e5m2 val) {
    return cpu_fp8_e5m2_to_float_lut[val.bits];
}

static inline double cpu_fp8_e5m2_to_double(cpu_fp8_e5m2 val) {
    return (double)cpu_fp8_e5m2_to_float_lut[val.bits];
}

static inline cpu_fp8_e5m2 cpu_float_to_fp8_e5m2(float val) {
    cpu_fp8_e5m2 result;

    /* Handle special cases */
    if (isnan(val)) {
        result.bits = 0;
        return result;
    }

    /* Extract sign via bit pattern (strict-aliasing-safe) */
    uint32_t fbits;
    memcpy(&fbits, &val, sizeof(fbits));
    uint32_t sign = (fbits >> 31) & 1;
    float absval = fabsf(val);

    /* Saturation: >= is intentional. 0x7B encodes exactly 57344.0, so absval == MAX_VAL
     * short-circuits to the same result the rounding path would produce. */
    if (absval >= E5M2_MAX_VAL) {
        result.bits = (uint8_t)((sign << 7) | 0x7B);  /* Max magnitude */
        return result;
    }

    /* Underflow to zero */
    if (absval < E5M2_MIN_SUBNORMAL * 0.5f) {
        result.bits = (uint8_t)(sign << 7);
        return result;
    }

    /* Extract FP32 exponent and mantissa */
    int exp32 = (int)((fbits >> 23) & 0xFF) - 127;
    uint32_t mant32 = fbits & 0x7FFFFFu;

    /* Compute FP8 exponent */
    int exp8 = exp32 + E5M2_BIAS;

    /* Handle subnormals */
    /* NOTE: Subnormal rounding omits shifted-out bits from sticky calculation.
       Max error: 1 ULP of FP8 E5M2 subnormal (2^-16). Below quantization floor; no fix required. */
    if (exp8 <= 0) {
        int shift = 1 - exp8;
        if (shift >= 24) {
            result.bits = (uint8_t)(sign << 7);  /* Underflow to zero (shift >= 24 is UB) */
            return result;
        }
        mant32 = (mant32 | 0x800000u) >> shift;
        exp8 = 0;
    } else if (exp8 >= 31) {
        result.bits = (uint8_t)((sign << 7) | 0x7B);
        return result;
    }

    /* Round mantissa to 2 bits (round-to-nearest-even) */
    uint32_t round_bit = (mant32 >> 20) & 1;
    uint32_t sticky = mant32 & ((1u << 20) - 1);
    uint32_t mant8 = mant32 >> 21;
    if (round_bit && (sticky || (mant8 & 1))) {
        mant8++;
    }
    if (mant8 >= 4) {
        mant8 = 0;
        exp8++;
        if (exp8 >= 31) {
            result.bits = (uint8_t)((sign << 7) | 0x7B);
            return result;
        }
    }

    result.bits = (uint8_t)((sign << 7) | ((uint32_t)exp8 << 2) | (mant8 & 0x3u));
    return result;
}

static inline cpu_fp8_e5m2 cpu_double_to_fp8_e5m2(double val) {
    /* Defense-in-depth: clamp before double→float narrowing to prevent UB
     * (C99 §6.3.1.5: double→float overflow is undefined behavior).
     * Pre-scaling (Phase 9E) ensures values are in FP8 range ⊂ FP32 range,
     * so this clamp is redundant under correct operation. Consistent with
     * the OpenCL (Step 9B.3) and Vulkan (Step 9D.2) backends. */
    if (val > (double)FLT_MAX) val = (double)FLT_MAX;
    if (val < -(double)FLT_MAX) val = -(double)FLT_MAX;
    return cpu_float_to_fp8_e5m2((float)val);
}

/* FP16 conversion — guarded by _Float16 availability */
#if defined(HAS_FLOAT16) && HAS_FLOAT16
static inline _Float16 cpu_fp8_e5m2_to_half(cpu_fp8_e5m2 val) {
    return (_Float16)cpu_fp8_e5m2_to_float_lut[val.bits];
}

static inline cpu_fp8_e5m2 cpu_half_to_fp8_e5m2(_Float16 val) {
    return cpu_float_to_fp8_e5m2((float)val);
}
#endif

/* --- FP8 SIMD/scalar dispatch functions for cpu_precision.h token-pasting ---
 *
 * These functions follow the naming convention used by cpu_simd.h:
 *   simd_load_real_<SUFFIX>, simd_store_real_<SUFFIX>,
 *   scalar_load_real_<SUFFIX>, scalar_store_real_<SUFFIX>
 *
 * With STORAGE_SUFFIX=fp8e4m3 or fp8e5m2, the cpu_precision.h macros
 * expand to these functions via token pasting.
 *
 * SIMD operations use scalar loops — AVX-512 has no native FP8 instructions.
 *
 * Requires cpu_simd.h to be included first (for simd_float, SIMD_WIDTH, etc.).
 */
#ifdef CPU_SIMD_H

/* --- FP8 E4M3 ↔ float SIMD/scalar --- */

static inline simd_float simd_load_real_fp8e4m3(const cpu_fp8_e4m3* p) {
    float tmp[SIMD_WIDTH];
    for (int i = 0; i < SIMD_WIDTH; i++) tmp[i] = cpu_fp8_e4m3_to_float(p[i]);
    return simd_load(tmp);
}

static inline void simd_store_real_fp8e4m3(cpu_fp8_e4m3* p, simd_float v) {
    float tmp[SIMD_WIDTH];
    simd_store(tmp, v);
    for (int i = 0; i < SIMD_WIDTH; i++) p[i] = cpu_float_to_fp8_e4m3(tmp[i]);
}

static inline float scalar_load_real_fp8e4m3(const cpu_fp8_e4m3* p) {
    return cpu_fp8_e4m3_to_float(*p);
}

static inline void scalar_store_real_fp8e4m3(cpu_fp8_e4m3* p, float v) {
    *p = cpu_float_to_fp8_e4m3(v);
}

/* --- FP8 E5M2 ↔ float SIMD/scalar --- */

static inline simd_float simd_load_real_fp8e5m2(const cpu_fp8_e5m2* p) {
    float tmp[SIMD_WIDTH];
    for (int i = 0; i < SIMD_WIDTH; i++) tmp[i] = cpu_fp8_e5m2_to_float(p[i]);
    return simd_load(tmp);
}

static inline void simd_store_real_fp8e5m2(cpu_fp8_e5m2* p, simd_float v) {
    float tmp[SIMD_WIDTH];
    simd_store(tmp, v);
    for (int i = 0; i < SIMD_WIDTH; i++) p[i] = cpu_float_to_fp8_e5m2(tmp[i]);
}

static inline float scalar_load_real_fp8e5m2(const cpu_fp8_e5m2* p) {
    return cpu_fp8_e5m2_to_float(*p);
}

static inline void scalar_store_real_fp8e5m2(cpu_fp8_e5m2* p, float v) {
    *p = cpu_float_to_fp8_e5m2(v);
}

#endif /* CPU_SIMD_H */

#endif /* CPU_FP8_H */
