# src/shared/kernel_contracts/phase_2_learn_A_production.py
"""Phase 2A (Gradient Production) kernel contracts — populated from kernels.cl.h."""
from . import (
    BufferParamSpec, KernelContract, KernelContractBlock, LocalMemorySpec,
    PaddingContract, PlacementContract, ScalarParamSpec,
)

compute_probs_loss_cce_contract = KernelContract(
    kernel_name="compute_probs_loss_cce_chunk",
    contract_block=KernelContractBlock(
        holistic_constraints="All constraints are defined by the parameter commentary blocks.",
        idempotency="Associatively Non-Idempotent",
        synchronization_model="Partial Renderer for probabilities output.",
        behavioral_invariants=("Fused, indivisible unit for numerically stable Softmax calculation.",),
    ),
    buffer_params=(
        BufferParamSpec(
            name="src_buffer_GLOBAL_logits", flow="src", memory_scope="GLOBAL",
            tensor_shape=("total_modules_count", "total_batch_count", "padded_total_output_class_count"),
            padding_contract=PaddingContract("CACHE", "output_class_count padded for alignment"),
            calculability_proof=("total_modules_count", "total_batch_count", "padded_total_output_class_count"),
            validation_preconditions=("tile within bounds",),
            precision_role="storage",
        ),
        BufferParamSpec(
            name="src_buffer_GLOBAL_CONST_temps", flow="src", memory_scope="GLOBAL_CONST",
            tensor_shape=("total_modules_count",),
            padding_contract=PaddingContract("NONE", None),
            calculability_proof=("total_modules_count",),
            validation_preconditions=("exact allocation size",),
            precision_role="state",
        ),
        BufferParamSpec(
            name="src_buffer_GLOBAL_targets", flow="src", memory_scope="GLOBAL",
            tensor_shape=("total_batch_count",),
            padding_contract=PaddingContract("NONE", None),
            calculability_proof=("total_batch_count",),
            validation_preconditions=("values in [0, output_class_count-1]",),
            precision_role=None,
        ),
        BufferParamSpec(
            name="src_buffer_GLOBAL_sample_mask", flow="src", memory_scope="GLOBAL",
            tensor_shape=("total_batch_count",),
            padding_contract=PaddingContract("NONE", None),
            calculability_proof=("total_batch_count",),
            validation_preconditions=("exact allocation size",),
            precision_role="storage",
        ),
        BufferParamSpec(
            name="dest_buffer_GLOBAL_partial_probs", flow="dest", memory_scope="GLOBAL",
            tensor_shape=("total_tile_count", "modules_per_chunk", "total_batch_count", "classes_per_chunk"),
            padding_contract=PaddingContract("NONE", None),
            calculability_proof=("total_tile_count", "modules_per_chunk", "total_batch_count", "classes_per_chunk"),
            validation_preconditions=("tile write index valid",),
            precision_role="storage",
        ),
        BufferParamSpec(
            name="dest_buffer_GLOBAL_final_loss", flow="dest", memory_scope="GLOBAL",
            tensor_shape=("total_modules_count", "total_batch_count"),
            padding_contract=PaddingContract("NONE", None),
            calculability_proof=("total_modules_count", "total_batch_count"),
            validation_preconditions=("host zero-initialize",),
            precision_role="compute",
        ),
    ),
    scalar_params=(
        ScalarParamSpec("flat_tile_index", "src", "NATURAL"),
        ScalarParamSpec("num_class_chunks", "src", "NATURAL"),
        ScalarParamSpec("classes_per_chunk", "src", "NATURAL"),
        ScalarParamSpec("modules_per_chunk", "src", "NATURAL"),
        ScalarParamSpec("total_batch_count", "src", "NATURAL"),
        ScalarParamSpec("total_output_class_count", "src", "NATURAL"),
        ScalarParamSpec("padded_total_output_class_count", "src", "NATURAL"),
        ScalarParamSpec("total_modules_count", "src", "NATURAL"),
        ScalarParamSpec("total_tile_count", "src", "NATURAL"),
    ),
    local_memory=(),
    placement=PlacementContract(strategy="grid_mod_cls", key_domain=None, context_params={}),
)

compute_probs_loss_bce_contract = KernelContract(
    kernel_name="compute_probs_loss_bce_chunk",
    contract_block=KernelContractBlock(
        holistic_constraints="All constraints are defined by the parameter commentary blocks.",
        idempotency="Strictly Idempotent",
        synchronization_model="Dual Partial Renderer.",
        behavioral_invariants=None,
    ),
    buffer_params=(
        BufferParamSpec(
            name="src_buffer_GLOBAL_logits", flow="src", memory_scope="GLOBAL",
            tensor_shape=("total_modules_count", "total_batch_count", "padded_total_output_class_count"),
            padding_contract=PaddingContract("CACHE", "output_class_count padded for alignment"),
            calculability_proof=("total_modules_count", "total_batch_count", "padded_total_output_class_count"),
            validation_preconditions=("tile within bounds",),
            precision_role="storage",
        ),
        BufferParamSpec(
            name="src_buffer_GLOBAL_CONST_temps", flow="src", memory_scope="GLOBAL_CONST",
            tensor_shape=("total_modules_count",),
            padding_contract=PaddingContract("NONE", None),
            calculability_proof=("total_modules_count",),
            validation_preconditions=("exact allocation size",),
            precision_role="state",
        ),
        BufferParamSpec(
            name="src_buffer_GLOBAL_targets", flow="src", memory_scope="GLOBAL",
            tensor_shape=("total_batch_count", "padded_total_output_class_count"),
            padding_contract=PaddingContract("CACHE", "output_class_count padded for alignment"),
            calculability_proof=("total_batch_count", "padded_total_output_class_count"),
            validation_preconditions=("exact allocation size",),
            precision_role="storage",
        ),
        BufferParamSpec(
            name="src_buffer_GLOBAL_sample_mask", flow="src", memory_scope="GLOBAL",
            tensor_shape=("total_batch_count",),
            padding_contract=PaddingContract("NONE", None),
            calculability_proof=("total_batch_count",),
            validation_preconditions=("exact allocation size",),
            precision_role="storage",
        ),
        BufferParamSpec(
            name="dest_buffer_GLOBAL_partial_probs", flow="dest", memory_scope="GLOBAL",
            tensor_shape=("total_tile_count", "modules_per_chunk", "total_batch_count", "classes_per_chunk"),
            padding_contract=PaddingContract("NONE", None),
            calculability_proof=("total_tile_count", "modules_per_chunk", "total_batch_count", "classes_per_chunk"),
            validation_preconditions=("tile write index valid",),
            precision_role="storage",
        ),
        BufferParamSpec(
            name="dest_buffer_GLOBAL_partial_loss", flow="dest", memory_scope="GLOBAL",
            tensor_shape=("total_tile_count", "modules_per_chunk", "total_batch_count"),
            padding_contract=PaddingContract("NONE", None),
            calculability_proof=("total_tile_count", "modules_per_chunk", "total_batch_count"),
            validation_preconditions=("tile write index valid",),
            precision_role="storage",
        ),
    ),
    scalar_params=(
        ScalarParamSpec("flat_tile_index", "src", "NATURAL"),
        ScalarParamSpec("num_class_chunks", "src", "NATURAL"),
        ScalarParamSpec("classes_per_chunk", "src", "NATURAL"),
        ScalarParamSpec("modules_per_chunk", "src", "NATURAL"),
        ScalarParamSpec("total_batch_count", "src", "NATURAL"),
        ScalarParamSpec("total_output_class_count", "src", "NATURAL"),
        ScalarParamSpec("padded_total_output_class_count", "src", "NATURAL"),
        ScalarParamSpec("total_modules_count", "src", "NATURAL"),
        ScalarParamSpec("total_tile_count", "src", "NATURAL"),
    ),
    local_memory=(),
    placement=PlacementContract(strategy="grid_mod_cls", key_domain=None, context_params={}),
)

calculate_module_param_grads_contract = KernelContract(
    kernel_name="calculate_module_param_grads_chunk",
    contract_block=KernelContractBlock(
        holistic_constraints="All constraints are defined by the parameter commentary blocks.",
        idempotency="Associatively Non-Idempotent",
        synchronization_model="Dual Partial Renderer.",
        behavioral_invariants=None,
    ),
    buffer_params=(
        BufferParamSpec(
            name="src_buffer_GLOBAL_hidden_activations", flow="src", memory_scope="GLOBAL",
            tensor_shape=("total_batch_count", "padded_hidden_count"),
            padding_contract=PaddingContract("CACHE", "Padded to alignment"),
            calculability_proof=("total_batch_count", "padded_hidden_count"),
            validation_preconditions=("batch slice within bounds",),
            precision_role="storage",
        ),
        BufferParamSpec(
            name="src_buffer_GLOBAL_partial_probs", flow="src", memory_scope="GLOBAL",
            tensor_shape=("total_tile_count", "modules_per_chunk", "total_batch_count", "classes_per_chunk"),
            padding_contract=PaddingContract("NONE", None),
            calculability_proof=("total_tile_count", "modules_per_chunk", "total_batch_count", "classes_per_chunk"),
            validation_preconditions=("tile within bounds",),
            precision_role="storage",
        ),
        BufferParamSpec(
            name="src_buffer_GLOBAL_targets", flow="src", memory_scope="GLOBAL",
            tensor_shape=("varies",),
            padding_contract=PaddingContract("NONE", None),
            calculability_proof=("problem_type",),
            validation_preconditions=("type-punned pointer; host provides correct buffer",),
            precision_role=None,
        ),
        BufferParamSpec(
            name="src_buffer_GLOBAL_sample_mask", flow="src", memory_scope="GLOBAL",
            tensor_shape=("total_batch_count",),
            padding_contract=PaddingContract("NONE", None),
            calculability_proof=("total_batch_count",),
            validation_preconditions=("batch slice within bounds",),
            precision_role="storage",
        ),
        BufferParamSpec(
            name="dest_buffer_GLOBAL_partial_grad_weights_module", flow="dest", memory_scope="GLOBAL",
            tensor_shape=("total_tile_count", "modules_per_chunk", "padded_hidden_count", "classes_per_chunk"),
            padding_contract=PaddingContract("NONE", None),
            calculability_proof=("total_tile_count", "modules_per_chunk", "padded_hidden_count", "classes_per_chunk"),
            validation_preconditions=("tile write index valid",),
            precision_role="storage",
        ),
        BufferParamSpec(
            name="dest_buffer_GLOBAL_partial_grad_biases_module", flow="dest", memory_scope="GLOBAL",
            tensor_shape=("total_tile_count", "modules_per_chunk", "classes_per_chunk"),
            padding_contract=PaddingContract("NONE", None),
            calculability_proof=("total_tile_count", "modules_per_chunk", "classes_per_chunk"),
            validation_preconditions=("tile write index valid",),
            precision_role="storage",
        ),
    ),
    scalar_params=(
        ScalarParamSpec("problem_type", "src", "FLAG"),
        ScalarParamSpec("flat_tile_index", "src", "NATURAL"),
        ScalarParamSpec("batch_chunk_offset", "src", "NATURAL"),
        ScalarParamSpec("batch_chunk_count", "src", "NATURAL"),
        ScalarParamSpec("num_class_chunks", "src", "NATURAL"),
        ScalarParamSpec("classes_per_chunk", "src", "NATURAL"),
        ScalarParamSpec("modules_per_chunk", "src", "NATURAL"),
        ScalarParamSpec("total_batch_count", "src", "NATURAL"),
        ScalarParamSpec("hidden_count", "src", "NATURAL"),
        ScalarParamSpec("padded_hidden_count", "src", "NATURAL"),
        ScalarParamSpec("total_output_class_count", "src", "NATURAL"),
        ScalarParamSpec("padded_total_output_class_count", "src", "NATURAL"),
        ScalarParamSpec("total_modules_count", "src", "NATURAL"),
        ScalarParamSpec("total_tile_count", "src", "NATURAL"),
    ),
    local_memory=(
        LocalMemorySpec("reduction_tile", "get_local_size(0) * sizeof(COMPUTE_TYPE)"),
    ),
    placement=PlacementContract(strategy="grid_mod_cls", key_domain=None, context_params={}),
)
